import React from "react";

/**
 * AIArtifactsPanel Component
 * 
 * Displays artifacts (code, tables, images, JSON, etc.) generated by the AI.
 * Supports multiple artifact types and provides UI for viewing/editing them.
 * 
 * @param {Object} props
 * @param {Object} [props.state] - Optional: pre-computed state from useAIState
 * @param {Function} [props.onArtifactSelect] - Callback when artifact is selected
 * @param {React.CSSProperties} [props.style] - Custom styles
 * @param {string} [props.className] - CSS class name
 * 
 * @example
 * import { AIArtifactsPanel } from "@ai-ui/react";
 * 
 * function MyArtifactsPanel() {
 *   const { state } = useAISession({ transport });
 *   
 *   return (
 *     <AIArtifactsPanel 
 *       state={state}
 *       onArtifactSelect={(artifact) => {
 *         console.log("Selected:", artifact);
 *       }}
 *     />
 *   );
 * }
 */
export const AIArtifactsPanel = React.forwardRef(
  ({ state, onArtifactSelect, style, className, ...props }, ref) => {
    const artifacts = state?.artifacts || [];

    const renderArtifactContent = (artifact) => {
      if (!artifact.content) return "No content";

      switch (artifact.type) {
        case "code":
          return (
            <pre>
              <code>{artifact.content}</code>
            </pre>
          );
        case "json":
          return (
            <pre>
              <code>{JSON.stringify(artifact.content, null, 2)}</code>
            </pre>
          );
        case "table":
          return (
            <table>
              <tbody>
                {Array.isArray(artifact.content) && artifact.content.length > 0 && (
                  <>
                    <tr>
                      {Object.keys(artifact.content[0]).map((key) => (
                        <th key={key}>{key}</th>
                      ))}
                    </tr>
                    {artifact.content.map((row, idx) => (
                      <tr key={idx}>
                        {Object.values(row).map((val, colIdx) => (
                          <td key={colIdx}>{val}</td>
                        ))}
                      </tr>
                    ))}
                  </>
                )}
              </tbody>
            </table>
          );
        case "image":
          return <img src={artifact.content} alt={artifact.title} />;
        case "text":
        default:
          return <div>{artifact.content}</div>;
      }
    };

    return (
      <div
        ref={ref}
        className={`ai-artifacts-panel ${className || ""}`}
        style={style}
        data-testid="ai-artifacts-panel"
        {...props}
      >
        <div className="ai-artifacts-panel-header">Artifacts</div>
        {artifacts.length === 0 ? (
          <div className="ai-artifacts-panel-empty" data-testid="artifacts-empty">
            No artifacts generated yet
          </div>
        ) : (
          <div className="ai-artifacts-panel-list">
            {artifacts.map((artifact) => (
              <div
                key={artifact.id}
                className={`ai-artifact ai-artifact-${artifact.type}`}
                data-testid={`artifact-${artifact.id}`}
                onClick={() => onArtifactSelect?.(artifact)}
              >
                <div className="ai-artifact-header">
                  <span className="ai-artifact-title">{artifact.title}</span>
                  <span className="ai-artifact-type" data-testid={`artifact-type-${artifact.id}`}>
                    {artifact.type}
                  </span>
                  {artifact.status && (
                    <span className="ai-artifact-status" data-testid={`artifact-status-${artifact.id}`}>
                      {artifact.status}
                    </span>
                  )}
                </div>
                <div className="ai-artifact-content">
                  {renderArtifactContent(artifact)}
                </div>
                {artifact.error && (
                  <div className="ai-artifact-error">
                    Error: {artifact.error}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }
);

AIArtifactsPanel.displayName = "AIArtifactsPanel";
