export const AI_EVENT_TYPES = {
  SESSION_STARTED: "session.started",
  MESSAGE_STARTED: "message.started",
  TEXT_DELTA: "text.delta",
  REASONING_DELTA: "reasoning.delta",
  TOOL_CALL_STARTED: "tool.call.started",
  TOOL_CALL_DELTA: "tool.call.delta",
  TOOL_CALL_COMPLETED: "tool.call.completed",
  TOOL_APPROVAL_REQUIRED: "tool.approval.required",
  ARTIFACT_CREATED: "artifact.created",
  CITATION_ADDED: "citation.added",
  MESSAGE_COMPLETED: "message.completed",
  ERROR_OCCURRED: "error.occurred",
  SESSION_COMPLETED: "session.completed"
};

export const CANONICAL_EVENT_SEQUENCE = [
  AI_EVENT_TYPES.SESSION_STARTED,
  AI_EVENT_TYPES.MESSAGE_STARTED,
  AI_EVENT_TYPES.TEXT_DELTA,
  AI_EVENT_TYPES.REASONING_DELTA,
  AI_EVENT_TYPES.TOOL_CALL_STARTED,
  AI_EVENT_TYPES.TOOL_CALL_DELTA,
  AI_EVENT_TYPES.TOOL_CALL_COMPLETED,
  AI_EVENT_TYPES.TOOL_APPROVAL_REQUIRED,
  AI_EVENT_TYPES.ARTIFACT_CREATED,
  AI_EVENT_TYPES.CITATION_ADDED,
  AI_EVENT_TYPES.MESSAGE_COMPLETED,
  AI_EVENT_TYPES.ERROR_OCCURRED,
  AI_EVENT_TYPES.SESSION_COMPLETED
];
